// Generated by CoffeeScript 1.9.3
(function() {
  var assert;

  assert = require("assert");

  describe('Conf util', function() {
    var conf;
    conf = require('./../lib/utils/conf');
    return describe('test', function() {
      return it('Shoul return 5', function() {
        return assert.equal(5, conf.test());
      });
    });
  });

}).call(this);
