language: node_js
node_js:
- '0.12'
after_success:
- if [ -n "$TRAVIS_TAG" ]; then sed -i.bak "s/0.0.0/$TRAVIS_TAG/g" package.json &&
  rm package.json.bak; fi
- npm run build
deploy:
  provider: npm
  email: muradbei@gmail.com
  api_key:
    secure: O9bScOI37fxn5exqb5jKUscxTSpqzLOetYh4e6X1HKxCCgg01FzMBDB/g96laQomq1PKsT6Hxkxk+mvV/X4xW8S54fhAz4gJvPnnlSqs0KRpGZIBrPCF0IrZ43+2eAOTd9AcC4J+AJb5CAm2T5gR1MppjIwMAjbuR0fpdnQJGQpd2UKTpZI9maZ3RGxvD0N36inLvxjDI8reiJbg1iqZM0irBvrIVgzQEANQ1exLNWMjswo0DUvRr3OCOV0T4KSbc9HMdlvWbi+wNqMhCX7/VGK/jjvDqhA89rqlGszbJHRkLPpoBn1n9tpKIRgJikhtGQTzN9jxkadq4V23ODYKYjprMy1OgGK8Ldmr/WI0VgOsRwEaHLQuVxlMoDPxxeRwdjXMGKtiTD0S0+wBpODL4QOX/9ogoKw8XbheQxvt6WyBV93cy01h9mtC0lGa3Hz1T0eTciHCQolnjmh+TehPHEOZJV65fGcaRQBkZuRs04SyHbdqNlAVaQyzv2bEgIAvFet9V9Z/8RZF4S/H6kgp2htK39RC2zozusmjUQkEH4Spjrt5xZhPWx65yYgOrafMwwghWBCqC10bVDLBkngpZ2ygz8XFqAl1lYmkpUT2JyVobNiRbSPL9H9nZtbXkLKPdwl0NoMGtEJ2nya0P4LW+Jb9xzXRDKwO40ZAZHUr4mw=
  on:
    tags: true
    repo: Aidbox/aidbox-cli
notifications:
  slack:
    secure: NOevH3YU2xNOEP0JuDLkCnNsXqC+2g+rOrwVVKg9PHOgLUDOTstLQqal4kioumWjagkv5MBPKekqoSBTwG04rv5NhwmlWXTGSLB0Rq33yWl1qM977AZiXv7wMfEIkFyqgsFpbPY+Elsr9FRbUYxZ7YLOAYhWqEQFrjJ6mNNA1iCLX86y7uWDhStyhAjRoz35uAi+Zm/Ml2Xc6mtm05yUxvT3/0eizCIznrOZR0fNMEe1hN6ySpNpcEYTDhb1KG9VLtbfFTu4jQoeb2/bFVZZaZbikb7LkNWAuP4bpoY9b1dGSBEKlfezMQFtfnsRVA3YTLJrzzv+NBhiOFVUVlQXkSh8nyjrCJ+teN6y5/1QCG3UPYl02qId3Z5Ym/6ZzT+MUpBxhrnWeFr+ORSmbotRlgsPkEyGv6XqvtqvOemoah4hTyGO0I3rwtwpWTmWM6c4VUb0WKInJr/gfOa3lf6K/r0zF+0AfVYDfGwBr/mSarGho0jpJQyB4/L0TVy9xMDhofJafHFk3qK84VaLIuo55QWoYlRNjqkes+QEHFotcYRuSveC12C+JkEMb90SwlK+bn9lWCdgFGqqHG8IMVB77Y46W5J+PhPbSyl/ci6FIDXaqSlP5usD6OPygosEjiSkjBjezy62qwCa8kOhb9nxHl0zN77lkL0d/zF5YZfEdRo=
