// Generated by CoffeeScript 1.9.3
(function() {
  var box, cli, conf, deploy, oauth, user;

  cli = require('cli');

  oauth = require('./utils/oauth');

  box = require('./utils/box');

  user = require('./utils/user');

  deploy = require('./utils/deploy');

  conf = require('./utils/conf');

  exports.run = function() {
    cli.parse(null, ['v', 'login', 'logout', 'box', 'user', 'deploy', 'test']);
    return cli.main(function(args, options) {
      switch (cli.command) {
        case 'login':
          return oauth.login(args);
        case 'logout':
          return oauth.logout();
        case 'box':
          return box(args, options);
        case 'user':
          return user(args, options);
        case 'deploy':
          return deploy(args, options);
        case 'v':
          return cli.ok("v0.4.8");
        case 'test':
          return conf.homedir();
      }
    });
  };

}).call(this);
