// Generated by CoffeeScript 1.12.6
(function() {
  var cli, conf, confFileName, deleteConfFile, fs, home, homedir, path, readConf, readConfFile, writeConfFile;

  fs = require('fs');

  cli = require('cli');

  path = require('path');

  home = process.env[process.platform === 'win32' ? 'USERPROFILE' : 'HOME'];

  conf = {
    server: process.env.AIDBOX_SERVER || "https://aidbox.io",
    root: 'root'
  };

  homedir = function(username) {
    if (username) {
      return path.resolve(path.dirname(home), username);
    } else {
      return home;
    }
  };

  confFileName = homedir() + '/.aidbox.json';

  readConfFile = function(fileName) {
    if (fs.existsSync(fileName)) {
      return JSON.parse(fs.readFileSync(fileName, 'utf8'));
    } else {
      return conf;
    }
  };

  writeConfFile = function(data) {
    return fs.writeFileSync(confFileName, JSON.stringify(data));
  };

  deleteConfFile = function() {
    return fs.unlink(confFileName, function() {
      return cli.ok("All session data are removed");
    });
  };

  readConf = function() {
    return readConfFile(confFileName);
  };

  module.exports = {
    conf: readConf,
    save: writeConfFile,
    clear: deleteConfFile,
    homedir: homedir
  };

}).call(this);
