// Generated by CoffeeScript 1.12.2
(function() {
  var archiver, cli, compress, conf, config, deploy, dist, distArchive, fs, helper, publish, rest;

  cli = require('cli');

  fs = require('fs');

  rest = require('./rest');

  archiver = require('archiver');

  config = require('./conf');

  helper = require('./helper');

  conf = config.conf();

  dist = 'dist';

  distArchive = './aidboxdist.tar.gz';

  compress = function(cb) {
    var archive, output;
    cli.info("Compress you app...");
    output = fs.createWriteStream(distArchive);
    output.on('close', cb);
    archive = archiver('tar', {
      gzip: true,
      gzipOptions: {
        level: 1
      }
    });
    archive.on('error', function(err) {
      return cli.error("Erro when compress: " + err);
    }).pipe(output);
    return archive.finalize();
  };

  publish = function() {
    var fileName, stats;
    cli.info("Publish app...");
    fileName = distArchive;
    stats = fs.statSync(fileName);
    return rest.post('/deploy', {
      multipart: true,
      data: {
        file: rest.file(fileName, null, stats.size, null, 'application/x-gzip')
      }
    }, conf.box.host).on('complete', function(data, response) {
      return helper.catchError(data, response, function(data) {
        cli.ok(data.message + (" in box [" + conf.box.id + "]"));
        return fs.unlink(distArchive, function() {
          return cli.ok("Tmp files removed");
        });
      });
    }).on('error', helper.errHandler);
  };

  deploy = function(args, options) {
    dist = args[0] || dist;
    return compress(publish);
  };

  module.exports = deploy;

}).call(this);
