// Generated by CoffeeScript 1.9.3
(function() {
  var Table, boxTable, boxTableFill, catchError, chars, cli, clone, errHandler, merge, tablePrint, userTable, userTableFill;

  cli = require('cli');

  Table = require('cli-table');

  chars = {
    'top': '',
    'top-mid': '',
    'top-left': '',
    'top-right': '',
    'bottom': '',
    'bottom-mid': '',
    'bottom-left': '',
    'bottom-right': '',
    'left': '',
    'left-mid': '',
    'mid': '',
    'mid-mid': '',
    'right': '',
    'right-mid': '',
    'middle': '|'
  };

  tablePrint = function(table) {
    console.log('');
    console.log(table.toString());
    return console.log('');
  };

  boxTableFill = function(data) {
    var table;
    table = new Table({
      chars: chars,
      head: ['ID', 'Host', 'Created'],
      colWidths: [15, 50, 30]
    });
    data.map(function(entry) {
      return table.push([entry.id, entry.host, entry.created_at]);
    });
    return table;
  };

  userTableFill = function(data) {
    var table;
    table = new Table({
      chars: chars,
      head: ['ID', 'Email'],
      colWidths: [5, 50]
    });
    data.map(function(entry) {
      return table.push([entry.id, entry.email]);
    });
    return table;
  };

  boxTable = function(data) {
    return tablePrint(boxTableFill(data));
  };

  userTable = function(data) {
    return tablePrint(userTableFill(data));
  };

  errHandler = function(e) {
    return cli.error('Problem with request: ' + e.message);
  };

  catchError = function(data, res, cb) {
    if (res.statusCode === 403) {
      cli.error('Access deny');
      return;
    }
    if (data instanceof Error) {
      cli.error(data.message);
      return cli.error(data);
    } else {
      return cb(data);
    }
  };

  clone = function(x) {
    return JSON.parse(JSON.stringify(x));
  };

  merge = function() {
    return Array.prototype.slice.call(arguments).reduce(function(acc, o) {
      var k, ref, v;
      ref = o || {};
      for (k in ref) {
        v = ref[k];
        acc[k] = v;
      }
      return acc;
    }, {});
  };

  module.exports = {
    merge: merge,
    boxTable: boxTable,
    userTable: userTable,
    errHandler: errHandler,
    catchError: catchError
  };

}).call(this);
