// Generated by CoffeeScript 1.12.6
(function() {
  var auth, cli, conf, config, helper, login, logout, read, rest;

  cli = require('cli');

  rest = require('./rest');

  read = require('read');

  config = require('./conf');

  helper = require('./helper');

  conf = config.conf();

  auth = function(username, password) {
    return rest.get('/boxes', {
      username: username,
      password: password,
      data: {
        grant_type: 'client_credentials',
        scope: 'ups'
      }
    }).on('complete', function(data, response) {
      return helper.catchError(data, response, function(data) {
        cli.ok("Auth success");
        conf.username = username;
        conf.password = password;
        return config.save(conf);
      });
    }).on('error', helper.errHandler);
  };

  login = function(arg) {
    var password, username;
    username = arg[0], password = arg[1];
    if (conf.username && conf.password) {
      return cli.info("You are logged in " + conf.username);
    } else {
      if (username && password) {
        return auth(username, password);
      } else {
        return read({
          prompt: "Login: "
        }, function(err, username) {
          if (err) {
            return cli.error(err);
          }
          return read({
            prompt: "Password: ",
            silent: true
          }, function(err, password) {
            if (err) {
              return cli.error(err);
            }
            return auth(username, password);
          });
        });
      }
    }
  };

  logout = function() {
    config.clear();
    return cli.ok("You are now logged out");
  };

  module.exports = {
    login: login,
    logout: logout
  };

}).call(this);
