// Generated by CoffeeScript 1.9.3
(function() {
  var cli, conf, config, helper, login, logout, read, rest;

  cli = require('cli');

  rest = require('restler');

  read = require('read');

  config = require('./conf');

  helper = require('./helper');

  conf = config.conf();

  login = function() {
    if (conf.username && conf.password) {
      return cli.info("You are logged in " + conf.username);
    } else {
      return read({
        prompt: "Login: "
      }, function(err, username) {
        if (err) {
          return cli.error(err);
        }
        return read({
          prompt: "Password: ",
          silent: true
        }, function(err, password) {
          if (err) {
            return cli.error(err);
          }
          return rest.get(conf.server + '/boxes', {
            username: username,
            password: password,
            data: {
              grant_type: 'client_credentials',
              scope: 'ups'
            }
          }).on('complete', function(data, response) {
            return helper.catchError(data, response, function(data) {
              cli.ok("Auth success");
              conf.username = username;
              conf.password = password;
              return config.save(conf);
            });
          }).on('error', helper.errHandler);
        });
      });
    }
  };

  logout = function() {
    config.clear();
    return cli.ok("You are now logged out");
  };

  module.exports = {
    login: login,
    logout: logout
  };

}).call(this);
