// Generated by CoffeeScript 1.9.3
(function() {
  var conf, config, restler;

  restler = require('restler');

  config = require('./conf');

  conf = config.conf();

  module.exports = {
    get: function(uri) {
      return restler.get("" + conf.server + uri, {
        username: conf.username,
        password: conf.password
      });
    }
  };

}).call(this);
