// Generated by CoffeeScript 1.12.6
(function() {
  var conf, config, helper, restler, xhr;

  restler = require('restler');

  config = require('./conf');

  helper = require('./helper');

  conf = config.conf();

  xhr = function(method, arg) {
    var at, host, params, uri;
    uri = arg[0], params = arg[1], host = arg[2];
    if (conf.box) {
      at = {
        query: {
          access_token: conf.box.access_token
        }
      };
    } else {
      at = {};
    }
    host = host || conf.server;
    return restler.request("" + host + uri, helper.merge({
      method: method,
      username: conf.username,
      password: conf.password,
      headers: {
        'Content-Type': 'application/json'
      },
      parser: restler.parsers.auto
    }, params, at));
  };

  module.exports = {
    get: function() {
      return xhr("get", arguments);
    },
    post: function() {
      return xhr("post", arguments);
    },
    file: restler.file
  };

}).call(this);
